[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_ldf_mode = deep+

board_build.usb_type = HID
build_flags = -Wl,--allow-multiple-definition
monitor_speed = 115200


[platformio]
default_envs = teensy41

